namespace CodeSharing.Core.Resources.Constants;

public enum FunctionCodeEnum
{
    DASHBOARD,

    CONTENT,
    CONTENT_CATEGORY,
    CONTENT_POST,
    CONTENT_COMMENT,
    CONTENT_REPORT,

    STATISTIC,
    STATISTIC_MONTHLY_NEWMEMBER,
    STATISTIC_MONTHLY_NEWPOST,
    STATISTIC_MONTHLY_COMMENT,

    SYSTEM,
    SYSTEM_USER,
    SYSTEM_ROLE,
    SYSTEM_FUNCTION,
    SYSTEM_PERMISSION
}